[build-system]
requires = ["setuptools>=62.3.2", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "selfcalframework"
authors = [
    {name = "Miguel Cárcamo", email = "miguel.carcamo@manchester.ac.uk"},
]
maintainers = [
    {name = "Miguel Cárcamo", email = "miguel.carcamo@manchester.ac.uk"},
]
description = "A Python object oriented framework to do self-calibration"
readme = "README.md"
license = {text = "GNU GPL"}
requires-python = "==3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dynamic = ["version", "dependencies"]

[project.urls]
Source = "https://github.com/miguelcarcamov/objectoriented_selfcal"

[tool.setuptools]
packages = ["selfcalframework"]
include-package-data = true

[tool.setuptools_scm]
write_to = "selfcalframework/_version.py"
