[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=65.5.0", "setuptools-scm", "wheel"]

[project]
authors = [
  {name = "Miguel Cárcamo", email = "miguel.carcamo@manchester.ac.uk"}
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
description = "A Python object oriented framework to do radio-interferometric self-calibration"
dynamic = ["version", "dependencies"]
license = {text = "GNU GPL"}
maintainers = [
  {name = "Miguel Cárcamo", email = "miguel.carcamo@manchester.ac.uk"}
]
name = "snow"
readme = "README.md"
requires-python = ">=3.10, <=3.11"

[project.urls]
Source = "https://github.com/miguelcarcamov/snow"

[tool.setuptools.packages.find]
include = ["snow*"]
namespaces = false
where = ["src"]

[tool.setuptools_scm]
write_to = "src/snow/_version.py"
